### ISSUE TITLE
Empty string in ports list in docker-compose file

### ISSUE THREAD

**Issue by dsryzhov** [Open-MBEE/mmsri#2]
trying to run docker-compose --build 
and receive the following error

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.elasticsearch.ports contains an invalid type, it should be a number, string, or an object

In docker-compose there is an empty string for port
https://github.com/Open-MBEE/mmsri/blob/develop/docker-compose.yml

      - 9200:9200
      - 9300:9300
      -

**Comment by dlamoris** [comment]
this has been fixed in latest develop
