### ISSUE TITLE
MMS has started but not responds

### ISSUE THREAD

**Issue by dsryzhov** [Open-MBEE/mmsri#3]
Trying to start mms but can't connetct to the running server via
http://localhost:8080/v3/swagger-ui.html

Receive
ERR_CONNECTION_REFUSED

0. I've done 
docker-compose --build

1. mms server is started 

mms              | 2020-11-05 10:45:29.084  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
mms              | 2020-11-05 10:45:31.447  INFO 1 --- [           main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
mms              | 2020-11-05 10:45:31.665  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 14 endpoint(s) beneath base path '/actuator'mms              | 2020-11-05 10:45:31.796  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
mms              | 2020-11-05 10:45:31.831  INFO 1 --- [           main] org.openmbee.mms.mmsri.MMSRIApplication  : Started MMSRIApplication in 35.686 seconds (JVM running for 38.105)

2. port 8080 are mapped from container to host 

docker container ls   

972526e2806f        mmsri_mms                                             "java -Djdk.tls.clie…"   9 minutes ago       Up 9 minutes        0.0.0.0:8080->8080/tcp                           mms
2bb962dfd815        docker.elastic.co/elasticsearch/elasticsearch:7.1.1   "/usr/local/bin/dock…"   9 minutes ago       Up 9 minutes        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   mmsri_elasticsearch_1
7fc67938a411        postgres:9-alpine                                     "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes        0.0.0.0:5432->5432/tcp                           mmsri_postgres_1
231e1ed4725c        minio/minio:latest                                    "/usr/bin/docker-ent…"   9 minutes ago       Up 9 minutes        0.0.0.0:9000->9000/tcp   

3. telnet returns connection time out

telnet 192.168.1.64 8080 (my windows 10 host)
Trying 192.168.1.64...
telnet: Unable to connect to remote host: Connection timed out

**Comment by sanbales** [comment]
I just tried doing this with `v4.0.0-b2` and it worked.

My System:
* Windows 10 (10.0.19041 Build 19041)
* Docker Desktop 2.5.0.0 (49427)
* Docker Engine: 19.03.13
* Docker Compose: 1.27.4

@dsryzhov: are you still seeing the same issue?

Confirm that I could log in using the Swagger UI:

![image](https://user-images.githubusercontent.com/1438114/99464397-07108d80-2906-11eb-89ec-7461cb19d197.png)

**Comment by dsryzhov** [comment]
Hi @sanbales,

No, there is no this issue now.
I've updated to last version and build docker images from sources.
Swagger is working and I also can log in Swagger UI. 

Regards,
Dmitry

**Comment by HuiJun** [comment]
Closing resolved
